In [1]:
from sklearn import tree
import pandas as pd
import dataframe_image as dfi
import os
import numpy as np
from matplotlib import pyplot as plt

In [22]:
df = pd.read_csv(os.path.join("data", "final_bitcoin2.csv"))
crypto = pd.read_csv(os.path.join("data", "price.csv"))
df = df.rename(columns={"Datetime":"date"})

In [23]:
sentiment0=[]
for i in range(len(df)):
    if df.loc[i,'negative']>0:
        sentiment0+=[0]
    elif df.loc[i,'positive']>0:
        sentiment0+=[2]        
    else:
        sentiment0+=[1]

In [24]:
df['sentiment']=sentiment0
df['sentiment'].value_counts()

df.head()

,Unnamed: 0,date,cleaned,negative,neutral,positive,comp,sentiment
0,0,2022-05-01,"['oh', 'think', 'im', 'pull', 'ass', 'bitcoin'...",0.304,0.696,0.000,-0.5423,0
1,1,2022-05-01,"['cryptic', 'oz', 'bitcoin', 'es', 'baloncesto...",0.000,1.000,0.000,0.0000,1
2,2,2022-05-01,"['un', 'long', 'sandbox', 'sandbox', 'crypto',...",0.000,1.000,0.000,0.0000,1
3,3,2022-05-01,"['realiz', 'attract', 'religion', 'asset', 'pr...",0.000,0.414,0.586,0.8360,2
4,4,2022-05-01,"['ridicul', 'stock', 'bitcoin', 'money', 'lite...",0.114,0.773,0.114,0.0000,0

In [25]:
crypto.reset_index(inplace=True)
crypto = crypto.drop(['index'], axis = 1)
crypto['date'] = pd.to_datetime(crypto['date'])
crypto['date'] = crypto['date'].dt.strftime('%Y-%m-%d')
crypto

,Unnamed: 0,bitcoin_price,ethereum_price,dogecoin_price,date,bitcoin_volume,ethereum_volume,dogecoin_volume
0,0,14884.979992,328.653136,0.003901,2020-05-19,5.967659e+10,2.045635e+10,3.159139e+08
1,1,14922.865925,326.538524,0.003891,2020-05-20,5.668974e+10,1.561838e+10,1.867668e+08
2,2,14452.798040,318.473767,0.003781,2020-05-21,5.283982e+10,1.582295e+10,1.764923e+08
3,3,13795.940128,302.899061,0.003681,2020-05-22,5.476526e+10,1.234986e+10,2.064283e+08
4,4,13971.494350,315.525952,0.003858,2020-05-23,4.238211e+10,1.627442e+10,2.184323e+08
...,...,...,...,...,...,...,...,...
725,725,42267.741872,2898.843244,0.127568,2022-05-14,1.031672e+11,3.457985e+10,1.679408e+09
726,726,43534.739233,2976.736395,0.129823,2022-05-15,3.714673e+10,2.075952e+10,9.658377e+08
727,727,45069.769903,3089.689306,0.134079,2022-05-16,3.302329e+10,2.071565e+10,7.538429e+08
728,728,42910.751665,2905.144652,0.126187,2022-05-17,4.075195e+10,2.877878e+10,7.785160e+08
729,729,43383.269503,2979.972928,0.128611,2022-05-18,3.550730e+10,2.418622e+10,7.598522e+08

In [26]:
eth_sentiment = df.groupby('date')['sentiment'].mean()
eth_sentiment = eth_sentiment.reset_index()
eth_sentiment

          date  sentiment
0   2022-05-01   1.017998
1   2022-05-02   1.035496
2   2022-05-03   1.024498
3   2022-05-04   1.065493
4   2022-05-05   1.019798
5   2022-05-06   1.041596
6   2022-05-07   1.018498
7   2022-05-08   0.972703
8   2022-05-09   0.954505
9   2022-05-10   0.996800
10  2022-05-11   0.948305
11  2022-05-12   0.966103
12  2022-05-13   0.973403
13  2022-05-14   0.995200
14  2022-05-15   0.979502

In [27]:
eth_price_sen = pd.merge(eth_sentiment, crypto,how='outer', on='date')
eth2 = eth_price_sen.drop(columns=["Unnamed: 0"], axis = 1)

In [28]:
eth_clean = eth2.dropna(subset=['sentiment'])

In [29]:
eth_clean

,date,sentiment,bitcoin_price,ethereum_price,dogecoin_price,bitcoin_volume,ethereum_volume,dogecoin_volume
0,2022-05-01,1.017998,53518.018858,3874.650573,0.180779,2.965347e+10,1.785574e+10,1.206468e+09
1,2022-05-02,1.035496,54531.860549,4008.085357,0.188247,3.517429e+10,2.050259e+10,1.306821e+09
2,2022-05-03,1.024498,54709.645087,4059.288782,0.186066,4.231498e+10,2.511270e+10,1.018619e+09
3,2022-05-04,1.065493,53180.614016,3921.344785,0.182778,3.249291e+10,1.806705e+10,7.256790e+08
4,2022-05-05,1.019798,54702.555595,4053.948028,0.187391,4.374783e+10,2.388912e+10,1.048635e+09
5,2022-05-06,1.041596,51400.311798,3866.281839,0.180483,5.250914e+10,2.929791e+10,1.573665e+09
6,2022-05-07,1.018498,51026.289235,3814.224690,0.180969,4.552599e+10,2.898637e+10,1.233530e+09
7,2022-05-08,0.972703,50259.004275,3731.605078,0.180549,2.702844e+10,1.770002e+10,1.007459e+09
8,2022-05-09,0.954505,48329.555540,3571.264784,0.176215,4.370554e+10,2.919468e+10,9.566095e+08
9,2022-05-10,0.996800,43512.077206,3234.184510,0.151046,8.390590e+10,4.943897e+10,1.727538e+09
10,2022-05-11,0.948305,44742.762308,3381.343683,0.156079,7.797426e+10,5.313215e+10,2.192481e+09
11,2022-05-12,0.966103,41707.475657,3001.696379,0.121610,9.518385e+10,6.714513e+10,3.325718e+09
12,2022-05-13,0.973403,42381.906502,2861.777398,0.120819,8.925408e+10,6.056449e+10,3.021156e+09
13,2022-05-14,0.995200,42267.741872,2898.843244,0.127568,1.031672e+11,3.457985e+10,1.679408e+09
14,2022-05-15,0.979502,43534.739233,2976.736395,0.129823,3.714673e+10,2.075952e+10,9.658377e+08

In [30]:
#Change the price reference to the relevant Crypto you want to analyse
eth_clean['Change BTC'] = eth_clean.bitcoin_price - eth_clean.bitcoin_price.shift(1)
eth_clean

<ipython-input-30-0197f0717c57>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth_clean['Change BTC'] = eth_clean.bitcoin_price - eth_clean.bitcoin_price.shift(1)

,date,sentiment,bitcoin_price,ethereum_price,dogecoin_price,bitcoin_volume,ethereum_volume,dogecoin_volume,Change BTC
0,2022-05-01,1.017998,53518.018858,3874.650573,0.180779,2.965347e+10,1.785574e+10,1.206468e+09,NaN
1,2022-05-02,1.035496,54531.860549,4008.085357,0.188247,3.517429e+10,2.050259e+10,1.306821e+09,1013.841691
2,2022-05-03,1.024498,54709.645087,4059.288782,0.186066,4.231498e+10,2.511270e+10,1.018619e+09,177.784538
3,2022-05-04,1.065493,53180.614016,3921.344785,0.182778,3.249291e+10,1.806705e+10,7.256790e+08,-1529.031071
4,2022-05-05,1.019798,54702.555595,4053.948028,0.187391,4.374783e+10,2.388912e+10,1.048635e+09,1521.941579
5,2022-05-06,1.041596,51400.311798,3866.281839,0.180483,5.250914e+10,2.929791e+10,1.573665e+09,-3302.243797
6,2022-05-07,1.018498,51026.289235,3814.224690,0.180969,4.552599e+10,2.898637e+10,1.233530e+09,-374.022563
7,2022-05-08,0.972703,50259.004275,3731.605078,0.180549,2.702844e+10,1.770002e+10,1.007459e+09,-767.284960
8,2022-05-09,0.954505,48329.555540,3571.264784,0.176215,4.370554e+10,2.919468e+10,9.566095e+08,-1929.448735
9,2022-05-10,0.996800,43512.077206,3234.184510,0.151046,8.390590e+10,4.943897e+10,1.727538e+09,-4817.478333
10,2022-05-11,0.948305,44742.762308,3381.343683,0.156079,7.797426e+10,5.313215e+10,2.192481e+09,1230.685102
11,2022-05-12,0.966103,41707.475657,3001.696379,0.121610,9.518385e+10,6.714513e+10,3.325718e+09,-3035.286651
12,2022-05-13,0.973403,42381.906502,2861.777398,0.120819,8.925408e+10,6.056449e+10,3.021156e+09,674.430845
13,2022-05-14,0.995200,42267.741872,2898.843244,0.127568,1.031672e+11,3.457985e+10,1.679408e+09,-114.164630
14,2022-05-15,0.979502,43534.739233,2976.736395,0.129823,3.714673e+10,2.075952e+10,9.658377e+08,1266.997362

In [31]:
eth_clean['BTC Movement'] = np.where(eth_clean['Change BTC']>0, 1, 0)
eth_clean

<ipython-input-31-b6de5222dfb6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth_clean['BTC Movement'] = np.where(eth_clean['Change BTC']>0, 1, 0)

,date,sentiment,bitcoin_price,ethereum_price,dogecoin_price,bitcoin_volume,ethereum_volume,dogecoin_volume,Change BTC,BTC Movement
0,2022-05-01,1.017998,53518.018858,3874.650573,0.180779,2.965347e+10,1.785574e+10,1.206468e+09,NaN,0
1,2022-05-02,1.035496,54531.860549,4008.085357,0.188247,3.517429e+10,2.050259e+10,1.306821e+09,1013.841691,1
2,2022-05-03,1.024498,54709.645087,4059.288782,0.186066,4.231498e+10,2.511270e+10,1.018619e+09,177.784538,1
3,2022-05-04,1.065493,53180.614016,3921.344785,0.182778,3.249291e+10,1.806705e+10,7.256790e+08,-1529.031071,0
4,2022-05-05,1.019798,54702.555595,4053.948028,0.187391,4.374783e+10,2.388912e+10,1.048635e+09,1521.941579,1
5,2022-05-06,1.041596,51400.311798,3866.281839,0.180483,5.250914e+10,2.929791e+10,1.573665e+09,-3302.243797,0
6,2022-05-07,1.018498,51026.289235,3814.224690,0.180969,4.552599e+10,2.898637e+10,1.233530e+09,-374.022563,0
7,2022-05-08,0.972703,50259.004275,3731.605078,0.180549,2.702844e+10,1.770002e+10,1.007459e+09,-767.284960,0
8,2022-05-09,0.954505,48329.555540,3571.264784,0.176215,4.370554e+10,2.919468e+10,9.566095e+08,-1929.448735,0
9,2022-05-10,0.996800,43512.077206,3234.184510,0.151046,8.390590e+10,4.943897e+10,1.727538e+09,-4817.478333,0
10,2022-05-11,0.948305,44742.762308,3381.343683,0.156079,7.797426e+10,5.313215e+10,2.192481e+09,1230.685102,1
11,2022-05-12,0.966103,41707.475657,3001.696379,0.121610,9.518385e+10,6.714513e+10,3.325718e+09,-3035.286651,0
12,2022-05-13,0.973403,42381.906502,2861.777398,0.120819,8.925408e+10,6.056449e+10,3.021156e+09,674.430845,1
13,2022-05-14,0.995200,42267.741872,2898.843244,0.127568,1.031672e+11,3.457985e+10,1.679408e+09,-114.164630,0
14,2022-05-15,0.979502,43534.739233,2976.736395,0.129823,3.714673e+10,2.075952e+10,9.658377e+08,1266.997362,1

In [32]:
#update the target to the right crypto
target = eth_clean["BTC Movement"]
target_names = ["sentiment", "bitcoin_price"]

In [33]:
data = eth_clean.drop(["BTC Movement", "date", "Change BTC"], axis=1)
feature_names = data.columns
data.head()

,sentiment,bitcoin_price,ethereum_price,dogecoin_price,bitcoin_volume,ethereum_volume,dogecoin_volume
0,1.017998,53518.018858,3874.650573,0.180779,2.965347e+10,1.785574e+10,1.206468e+09
1,1.035496,54531.860549,4008.085357,0.188247,3.517429e+10,2.050259e+10,1.306821e+09
2,1.024498,54709.645087,4059.288782,0.186066,4.231498e+10,2.511270e+10,1.018619e+09
3,1.065493,53180.614016,3921.344785,0.182778,3.249291e+10,1.806705e+10,7.256790e+08
4,1.019798,54702.555595,4053.948028,0.187391,4.374783e+10,2.388912e+10,1.048635e+09

In [34]:
# Split the data using train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [35]:
# Create a Decision Tree Classifier
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.25

In [36]:
# Fit the classifier to the data
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.0

In [37]:
# Bonus
# Create, fit, and score a Random Forest Classifier
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.2985019841269841, 'bitcoin_price'),
 (0.2781269841269841, 'dogecoin_volume'),
 (0.1829431216931217, 'ethereum_price'),
 (0.09865079365079366, 'sentiment'),
 (0.07433333333333333, 'dogecoin_price'),
 (0.059259259259259255, 'bitcoin_volume'),
 (0.008184523809523812, 'ethereum_volume')]

In [38]:
final = pd.DataFrame(sorted(zip(rf.feature_importances_, feature_names), reverse=True))
final

          0                1
0  0.298502    bitcoin_price
1  0.278127  dogecoin_volume
2  0.182943   ethereum_price
3  0.098651        sentiment
4  0.074333   dogecoin_price
5  0.059259   bitcoin_volume
6  0.008185  ethereum_volume

In [39]:
final.columns = ["Weighting %", "Variable"]
final

   Weighting %         Variable
0     0.298502    bitcoin_price
1     0.278127  dogecoin_volume
2     0.182943   ethereum_price
3     0.098651        sentiment
4     0.074333   dogecoin_price
5     0.059259   bitcoin_volume
6     0.008185  ethereum_volume

In [40]:
final1 = final[["Variable","Weighting %"]]

In [41]:
dfi.export(final1, 'images/BTC_forest.png')