In [1]:
from sklearn import tree
import pandas as pd
import os
import numpy as np

In [2]:
df = pd.read_csv(os.path.join("..","..","..", "data", "ethereum_cleaned.csv"))
crypto = pd.read_csv(os.path.join("..","..","..","data", "price.csv"))
df = df.rename(columns={"Datetime":"date"})

In [3]:
sentiment0=[]
for i in range(len(df)):
    if df.loc[i,'negative']>0:
        sentiment0+=[0]
    elif df.loc[i,'positive']>0:
        sentiment0+=[2]        
    else:
        sentiment0+=[1]

In [4]:
df['sentiment']=sentiment0
df['sentiment'].value_counts()

df.head()

,Unnamed: 0,date,cleaned,negative,neutral,positive,comp,sentiment
0,0,2022-05-01,"['eth', 'http', 'co', 'nolnum7c3k']",0.0,1.000,0.000,0.0000,1
1,1,2022-05-01,"['btc', 'xrp', 'xem', 'lisk', 'iost', 'sand', ...",0.0,0.725,0.275,0.5859,2
2,2,2022-05-01,"['eth', 'son', '3', 'dip', 'daha', 'yapacak', ...",0.0,1.000,0.000,0.0000,1
3,3,2022-05-01,"['tigray', 'emerg', 'famin', 'food', 'insecur'...",0.0,1.000,0.000,0.0000,1
4,4,2022-05-01,"['b', 'nu', 'binanc', 'live', 'nft', 'bnb', 'b...",0.0,1.000,0.000,0.0000,1

In [5]:
crypto.reset_index(inplace=True)
crypto = crypto.drop(['index'], axis = 1)
crypto['date'] = pd.to_datetime(crypto['date'])
crypto['date'] = crypto['date'].dt.strftime('%Y-%m-%d')
crypto

,Unnamed: 0,bitcoin_price,ethereum_price,dogecoin_price,date,bitcoin_volume,ethereum_volume,dogecoin_volume
0,0,14884.979992,328.653136,0.003901,2020-05-19,5.967659e+10,2.045635e+10,3.159139e+08
1,1,14922.865925,326.538524,0.003891,2020-05-20,5.668974e+10,1.561838e+10,1.867668e+08
2,2,14452.798040,318.473767,0.003781,2020-05-21,5.283982e+10,1.582295e+10,1.764923e+08
3,3,13795.940128,302.899061,0.003681,2020-05-22,5.476526e+10,1.234986e+10,2.064283e+08
4,4,13971.494350,315.525952,0.003858,2020-05-23,4.238211e+10,1.627442e+10,2.184323e+08
...,...,...,...,...,...,...,...,...
725,725,42267.741872,2898.843244,0.127568,2022-05-14,1.031672e+11,3.457985e+10,1.679408e+09
726,726,43534.739233,2976.736395,0.129823,2022-05-15,3.714673e+10,2.075952e+10,9.658377e+08
727,727,45069.769903,3089.689306,0.134079,2022-05-16,3.302329e+10,2.071565e+10,7.538429e+08
728,728,42910.751665,2905.144652,0.126187,2022-05-17,4.075195e+10,2.877878e+10,7.785160e+08
729,729,43383.269503,2979.972928,0.128611,2022-05-18,3.550730e+10,2.418622e+10,7.598522e+08

In [7]:
eth_sentiment = df.groupby('date')['sentiment'].mean()
eth_sentiment = eth_sentiment.reset_index()
eth_sentiment

          date  sentiment
0   2022-05-01   0.985601
1   2022-05-02   1.033497
2   2022-05-03   1.033497
3   2022-05-04   1.024498
4   2022-05-05   1.035296
5   2022-05-06   1.009999
6   2022-05-07   0.914609
7   2022-05-08   1.004800
8   2022-05-09   1.025097
9   2022-05-10   1.013399
10  2022-05-11   1.036796
11  2022-05-12   0.992501
12  2022-05-13   1.035196
13  2022-05-14   1.031497
14  2022-05-15   0.914209

In [8]:
eth_price_sen = pd.merge(eth_sentiment, crypto,how='outer', on='date')
eth2 = eth_price_sen.drop(columns=["Unnamed: 0"], axis = 1)

In [9]:
eth_clean = eth2.dropna(subset=['sentiment'])

In [10]:
eth_clean

,date,sentiment,bitcoin_price,ethereum_price,dogecoin_price,bitcoin_volume,ethereum_volume,dogecoin_volume
0,2022-05-01,0.985601,53518.018858,3874.650573,0.180779,2.965347e+10,1.785574e+10,1.206468e+09
1,2022-05-02,1.033497,54531.860549,4008.085357,0.188247,3.517429e+10,2.050259e+10,1.306821e+09
2,2022-05-03,1.033497,54709.645087,4059.288782,0.186066,4.231498e+10,2.511270e+10,1.018619e+09
3,2022-05-04,1.024498,53180.614016,3921.344785,0.182778,3.249291e+10,1.806705e+10,7.256790e+08
4,2022-05-05,1.035296,54702.555595,4053.948028,0.187391,4.374783e+10,2.388912e+10,1.048635e+09
5,2022-05-06,1.009999,51400.311798,3866.281839,0.180483,5.250914e+10,2.929791e+10,1.573665e+09
6,2022-05-07,0.914609,51026.289235,3814.224690,0.180969,4.552599e+10,2.898637e+10,1.233530e+09
7,2022-05-08,1.004800,50259.004275,3731.605078,0.180549,2.702844e+10,1.770002e+10,1.007459e+09
8,2022-05-09,1.025097,48329.555540,3571.264784,0.176215,4.370554e+10,2.919468e+10,9.566095e+08
9,2022-05-10,1.013399,43512.077206,3234.184510,0.151046,8.390590e+10,4.943897e+10,1.727538e+09
10,2022-05-11,1.036796,44742.762308,3381.343683,0.156079,7.797426e+10,5.313215e+10,2.192481e+09
11,2022-05-12,0.992501,41707.475657,3001.696379,0.121610,9.518385e+10,6.714513e+10,3.325718e+09
12,2022-05-13,1.035196,42381.906502,2861.777398,0.120819,8.925408e+10,6.056449e+10,3.021156e+09
13,2022-05-14,1.031497,42267.741872,2898.843244,0.127568,1.031672e+11,3.457985e+10,1.679408e+09
14,2022-05-15,0.914209,43534.739233,2976.736395,0.129823,3.714673e+10,2.075952e+10,9.658377e+08

In [11]:
eth_clean['Change ETH'] = eth_clean.ethereum_price - eth_clean.ethereum_price.shift(1)
eth_clean

<ipython-input-11-0bd4c86b2291>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth_clean['Change ETH'] = eth_clean.ethereum_price - eth_clean.ethereum_price.shift(1)

,date,sentiment,bitcoin_price,ethereum_price,dogecoin_price,bitcoin_volume,ethereum_volume,dogecoin_volume,Change ETH
0,2022-05-01,0.985601,53518.018858,3874.650573,0.180779,2.965347e+10,1.785574e+10,1.206468e+09,NaN
1,2022-05-02,1.033497,54531.860549,4008.085357,0.188247,3.517429e+10,2.050259e+10,1.306821e+09,133.434784
2,2022-05-03,1.033497,54709.645087,4059.288782,0.186066,4.231498e+10,2.511270e+10,1.018619e+09,51.203425
3,2022-05-04,1.024498,53180.614016,3921.344785,0.182778,3.249291e+10,1.806705e+10,7.256790e+08,-137.943997
4,2022-05-05,1.035296,54702.555595,4053.948028,0.187391,4.374783e+10,2.388912e+10,1.048635e+09,132.603243
5,2022-05-06,1.009999,51400.311798,3866.281839,0.180483,5.250914e+10,2.929791e+10,1.573665e+09,-187.666189
6,2022-05-07,0.914609,51026.289235,3814.224690,0.180969,4.552599e+10,2.898637e+10,1.233530e+09,-52.057149
7,2022-05-08,1.004800,50259.004275,3731.605078,0.180549,2.702844e+10,1.770002e+10,1.007459e+09,-82.619612
8,2022-05-09,1.025097,48329.555540,3571.264784,0.176215,4.370554e+10,2.919468e+10,9.566095e+08,-160.340294
9,2022-05-10,1.013399,43512.077206,3234.184510,0.151046,8.390590e+10,4.943897e+10,1.727538e+09,-337.080274
10,2022-05-11,1.036796,44742.762308,3381.343683,0.156079,7.797426e+10,5.313215e+10,2.192481e+09,147.159174
11,2022-05-12,0.992501,41707.475657,3001.696379,0.121610,9.518385e+10,6.714513e+10,3.325718e+09,-379.647304
12,2022-05-13,1.035196,42381.906502,2861.777398,0.120819,8.925408e+10,6.056449e+10,3.021156e+09,-139.918981
13,2022-05-14,1.031497,42267.741872,2898.843244,0.127568,1.031672e+11,3.457985e+10,1.679408e+09,37.065846
14,2022-05-15,0.914209,43534.739233,2976.736395,0.129823,3.714673e+10,2.075952e+10,9.658377e+08,77.893151

In [12]:
eth_clean['ETH Movement'] = np.where(eth_clean['Change ETH']>0, 1, 0)
eth_clean

<ipython-input-12-3b1cf600764e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eth_clean['ETH Movement'] = np.where(eth_clean['Change ETH']>0, 1, 0)

,date,sentiment,bitcoin_price,ethereum_price,dogecoin_price,bitcoin_volume,ethereum_volume,dogecoin_volume,Change ETH,ETH Movement
0,2022-05-01,0.985601,53518.018858,3874.650573,0.180779,2.965347e+10,1.785574e+10,1.206468e+09,NaN,0
1,2022-05-02,1.033497,54531.860549,4008.085357,0.188247,3.517429e+10,2.050259e+10,1.306821e+09,133.434784,1
2,2022-05-03,1.033497,54709.645087,4059.288782,0.186066,4.231498e+10,2.511270e+10,1.018619e+09,51.203425,1
3,2022-05-04,1.024498,53180.614016,3921.344785,0.182778,3.249291e+10,1.806705e+10,7.256790e+08,-137.943997,0
4,2022-05-05,1.035296,54702.555595,4053.948028,0.187391,4.374783e+10,2.388912e+10,1.048635e+09,132.603243,1
5,2022-05-06,1.009999,51400.311798,3866.281839,0.180483,5.250914e+10,2.929791e+10,1.573665e+09,-187.666189,0
6,2022-05-07,0.914609,51026.289235,3814.224690,0.180969,4.552599e+10,2.898637e+10,1.233530e+09,-52.057149,0
7,2022-05-08,1.004800,50259.004275,3731.605078,0.180549,2.702844e+10,1.770002e+10,1.007459e+09,-82.619612,0
8,2022-05-09,1.025097,48329.555540,3571.264784,0.176215,4.370554e+10,2.919468e+10,9.566095e+08,-160.340294,0
9,2022-05-10,1.013399,43512.077206,3234.184510,0.151046,8.390590e+10,4.943897e+10,1.727538e+09,-337.080274,0
10,2022-05-11,1.036796,44742.762308,3381.343683,0.156079,7.797426e+10,5.313215e+10,2.192481e+09,147.159174,1
11,2022-05-12,0.992501,41707.475657,3001.696379,0.121610,9.518385e+10,6.714513e+10,3.325718e+09,-379.647304,0
12,2022-05-13,1.035196,42381.906502,2861.777398,0.120819,8.925408e+10,6.056449e+10,3.021156e+09,-139.918981,0
13,2022-05-14,1.031497,42267.741872,2898.843244,0.127568,1.031672e+11,3.457985e+10,1.679408e+09,37.065846,1
14,2022-05-15,0.914209,43534.739233,2976.736395,0.129823,3.714673e+10,2.075952e+10,9.658377e+08,77.893151,1

In [13]:
target = eth_clean["ETH Movement"]
target_names = ["sentiment", "ethereum_price"]

In [14]:
data = eth_clean.drop(["ETH Movement", "date", "Change ETH"], axis=1)
feature_names = data.columns
data.head()

,sentiment,bitcoin_price,ethereum_price,dogecoin_price,bitcoin_volume,ethereum_volume,dogecoin_volume
0,0.985601,53518.018858,3874.650573,0.180779,2.965347e+10,1.785574e+10,1.206468e+09
1,1.033497,54531.860549,4008.085357,0.188247,3.517429e+10,2.050259e+10,1.306821e+09
2,1.033497,54709.645087,4059.288782,0.186066,4.231498e+10,2.511270e+10,1.018619e+09
3,1.024498,53180.614016,3921.344785,0.182778,3.249291e+10,1.806705e+10,7.256790e+08
4,1.035296,54702.555595,4053.948028,0.187391,4.374783e+10,2.388912e+10,1.048635e+09

In [15]:
# Split the data using train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [16]:
# Create a Decision Tree Classifier
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.75

In [17]:
# Fit the classifier to the data
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.75

In [18]:
# Bonus
# Create, fit, and score a Random Forest Classifier
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.28745039682539686, 'bitcoin_price'),
 (0.20746031746031748, 'bitcoin_volume'),
 (0.2001785714285714, 'sentiment'),
 (0.1144047619047619, 'ethereum_volume'),
 (0.07555555555555556, 'ethereum_price'),
 (0.0635515873015873, 'dogecoin_price'),
 (0.05139880952380952, 'dogecoin_volume')]